import test from 'test'

try{
    test.assert(true, 'true is true')
}catch(error){
    console.log(error)
    
}